### ISSUE TITLE
HtmlFrame Error

### ISSUE THREAD

**Issue by thegame4craft** [Andereoo/TkinterWeb#1]
Hello, i used this code:
`from tkinter import *
from tkinterweb import HtmlFrame
root = Tk()
frame = HtmlFrame(root)
frame.load_website("https://google.de")
frame.pack(fill="both", expand=True)
root.mainloop()
`

And this is my Exeption:
`Traceback (most recent call last):
  File "C:\Users\Robin\atomProjects\python\TkWebWin\main.py", line 4, in <module>
    frame = HtmlFrame(root)
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python38\Lib\site-packages\tkinterweb\html_frame.py", line 57, in __init__
    html = self.html = TkinterWeb(self, message_func, fontscale=float(fontscale), zoom=float(zoom))
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python38\Lib\site-packages\tkinterweb\tkhtml_bindings.py", line 116, in __init__
    load_tkhtml(master, get_tkhtml_folder())
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python38\Lib\site-packages\tkinterweb\tkhtml_bindings.py", line 64, in load_tkhtml
    master.tk.eval("package require Tkhtml")
_tkinter.TclError: couldn't load library "C:/Users/Robin/AppData/Local/Programs/Python/Python38/Lib/site-packages/tkinterweb/tkhtml/Windows/64-bit/Tkhtml/Tkhtml30.dll": No error`

I use Python 3.8.2 and pip 21.0.1 and HtmlFrame latest

If any infomation is missing, please answer down here

**Comment by Andereoo** [comment]
Hello thegame4craft,

Sorry that you are running into this issue. It seems that pip was missing the `Tkhtml30.dll` file. I just updated the package. Please try re-installing TkinterWeb by running `pip install --upgrade --force-reinstall tkinterweb`. Let me know if this resolves the issue or if the issue still persists!
