### ISSUE TITLE
drawcleanupcrashcmd is not supported on intel macos

### ISSUE THREAD

**Issue by gwelch-contegix** [Andereoo/TkinterWeb#111]
drawcleanupcrashcmd is not supported on intel (x86-64) macos

Stack trace:
```
$ python3 -m tkinterweb.__init__
Starting TkinterWeb for 64-bit Darwin with Python 3.12.2.

Traceback (most recent call last):
  File "/Users/temp/venv/lib/python3.12/site-packages/tkinterweb/bindings.py", line 107, in __init__
    tk.Widget.__init__(self, master, "html", cfg, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/tkinter/__init__.py", line 2648, in __init__
    self.tk.call(
_tkinter.TclError: unknown option "-drawcleanupcrashcmd"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/temp/venv/lib/python3.12/site-packages/tkinterweb/__init__.py", line 85, in <module>
    Demo()
  File "/Users/temp/venv/lib/python3.12/site-packages/tkinterweb/__init__.py", line 72, in __init__
    frame = HtmlFrame(root)
            ^^^^^^^^^^^^^^^
  File "/Users/temp/venv/lib/python3.12/site-packages/tkinterweb/htmlwidgets.py", line 49, in __init__
    self.html = html = TkinterWeb(self, message_func, HtmlFrame)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/temp/venv/lib/python3.12/site-packages/tkinterweb/bindings.py", line 110, in __init__
    tk.Widget.__init__(self, master, "html", cfg, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/tkinter/__init__.py", line 2648, in __init__
    self.tk.call(
_tkinter.TclError: unknown option "-drawcleanupcrashcmd"
```
version:
```console
$ pip show tkinterweb
Name: tkinterweb
Version: 3.24.7
Summary: HTML/CSS viewer for Tkinter
Home-page: https://github.com/Andereoo/TkinterWeb
Author: 
Author-email: 
License: MIT
Location: /Users/temp/venv/lib/python3.12/site-packages
Requires: pillow
Required-by: 
```
Check for drawcleanupcrashcmd in shared libs from TkinterWeb repository
```console
TkinterWeb/tkinterweb/tkhtml $ printf '%s\n' */*Tkhtml*
linux_armv7l/libTkhtml3.0.so
macosx_10_6_x86_64/libTkhtml3.0.dylib
macosx_11_0_arm64/libTkhtml3.0.dylib
manylinux1_i686/libTkhtml3.0.so
manylinux1_x86_64/libTkhtml3.0.so
win32/Tkhtml30.dll
win_amd64/Tkhtml30.dll

TkinterWeb/tkinterweb/tkhtml $ grep -l drawcleanupcrashcmd */*Tkhtml*
linux_armv7l/libTkhtml3.0.so
macosx_11_0_arm64/libTkhtml3.0.dylib
manylinux1_x86_64/libTkhtml3.0.so
win32/Tkhtml30.dll
win_amd64/Tkhtml30.dll
```

**Comment by Andereoo** [comment]
Hi @gwelch-contegix  @taipingeric!
Thanks for noticing this. It looks like I accidentally turned on the drawcleanupcrashcmd flag for intel mac, which doesn't support it yet...oops. It should work now!

**Comment by kurmasz** [comment]
I just installed 3.24.8 and I'm getting the same error.

**Comment by Andereoo** [comment]
Hi! Can you please send me the output of platform.system() and os.uname()?

**Comment by kurmasz** [comment]
Python 3.12.6 (main, Sep  7 2024, 05:15:33) [Clang 15.0.0 (clang-1500.1.0.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import  platform
>>> import os
>>> platform.system()
'Darwin'
>>> os.uname()
posix.uname_result(sysname='Darwin', nodename='kurmasz8AMD6T', release='23.6.0', version='Darwin Kernel Version 23.6.0: Fri Nov 15 15:13:28 PST 2024; root:xnu-10063.141.1.702.7~1/RELEASE_X86_64', machine='x86_64')

**Comment by Andereoo** [comment]
Thanks! Try upgrading to 3.24.9 and let me know if it works!

**Comment by kurmasz** [comment]
I got a seg fault.  (Although, it is not obviously coming from this package.)

Running this code:

```
from tkinterweb import HtmlFrame
import tkinter as tk

root = tk.Tk()
frame = HtmlFrame(root)
frame.load_website("http://www.example.com")
frame.pack(fill="both", expand=True)

root.mainloop()
```

Produced this result:


```
Starting TkinterWeb for 64-bit Darwin with Python 3.12.6.

Tkhtml3 successfully loaded from /Users/kurmasz/Documents/Courses/CIS371/Homework/PythonBrowser/lib/python3.12/site-packages/tkinterweb/tkhtml/binaries.

Welcome to TkinterWeb 3.24! 
https://github.com/Andereoo/TkinterWeb

Debugging messages are enabled. 
Use the parameter `messages_enabled = False` when calling HtmlFrame() to disable these messages.

Connecting to www.example.com.

Segmentation fault: 11
```

**Comment by Andereoo** [comment]
Does running `tkinterweb.Demo()` or loading some basic HTML (eg. via `load_html("<p>TEST</p>")`) still cause a seg fault?

**Comment by kurmasz** [comment]
Yes for the demo: 

```
Python 3.12.6 (main, Sep  7 2024, 05:15:33) [Clang 15.0.0 (clang-1500.1.0.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tkinterweb
>>> tkinterweb.Demo()
Starting TkinterWeb for 64-bit Darwin with Python 3.12.6.

Tkhtml3 successfully loaded from /Users/kurmasz/Documents/Courses/CIS371/Homework/PythonBrowser/lib/python3.12/site-packages/tkinterweb/tkhtml/binaries.

Welcome to TkinterWeb 3.24! 
https://github.com/Andereoo/TkinterWeb

Debugging messages are enabled. 
Use the parameter `messages_enabled = False` when calling HtmlFrame() to disable these messages.

Connecting to wiki.python.org.

Segmentation fault: 11
```

**Comment by kurmasz** [comment]
Same result for this code:

```
from tkinterweb import HtmlFrame
import tkinter as tk

root = tk.Tk()
frame = HtmlFrame(root)
frame.load_html('<h1>Hello, World!</h1>')
frame.pack(fill="both", expand=True)

root.mainloop()
```

**Comment by kurmasz** [comment]
For what it's worth: The seg fault happends during the main loop:

````
from tkinterweb import HtmlFrame
import tkinter as tk

root = tk.Tk()
print("Here 1")
frame = HtmlFrame(root)
print("Here 2")
# frame.load_website("http://www.example.com")
frame.load_html('<h1>Hello, World!</h1>')
print("Here 3")
frame.pack(fill="both", expand=True)
print("Here 4")
root.mainloop()
print("Here 5")
````

````
$ bin/python test.py 
Here 1
Starting TkinterWeb for 64-bit Darwin with Python 3.12.6.

Tkhtml3 successfully loaded from /Users/kurmasz/Documents/Courses/CIS371/Homework/PythonBrowser/lib/python3.12/site-packages/tkinterweb/tkhtml/binaries.

Welcome to TkinterWeb 3.24! 
https://github.com/Andereoo/TkinterWeb

Debugging messages are enabled. 
Use the parameter `messages_enabled = False` when calling HtmlFrame() to disable these messages.

Here 2
Here 3
Here 4
Segmentation fault: 11
````

**Comment by Andereoo** [comment]
I updated the binary for x86-64 MacOS to support drawcleanupcrashcmd. I don't get a seg fault when testing on Github Actions. Perhaps you'd be able to check if the latest version is still not working?

If it still doesn't work, would you be able to send me the output of te code below?
```
import tkinter
tcl = tkinter.Tcl()
print(tcl.call("info", "patchlevel"))
```

**Comment by kurmasz** [comment]
I'm still getting a segfault.  The output of your patchlevel code is

8.6.13

**Comment by Andereoo** [comment]
@gwelch-contegix Does this package work now, or are you also getting a segfault?

**Comment by gwelch-contegix** [comment]
Yes this works for me now

**Comment by Andereoo** [comment]
@kurmasz I'm afraid I can't replicate your issue. I am fairly confident that compiling the underlying Tkhtml binary on your system (the source code is at https://github.com/Andereoo/TkinterWeb-Tkhtml/) may fix the issue, but beyond that I don't think there's much else I can do for you at this point. I would be happy to provide tips if needed!
