### ISSUE TITLE
RPI install - "bad marshal data" - pip3 install tkinterweb

### ISSUE THREAD

**Issue by WGandy** [Andereoo/TkinterWeb#22]
Trying to install on a raspberry pi zero running 'Lite' but with openbox and lightdm.  I also had this issue when trying to install on a Mac. 

This may be an issue with distutils??  

`pi@raspberrypi:~ $ pip3 install tkinterweb
Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    from pip._internal import main
  File "/usr/lib/python3/dist-packages/pip/_internal/__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/cmdoptions.py", line 17, in <module>
    from pip._internal.locations import USER_CACHE_DIR, src_prefix
  File "/usr/lib/python3/dist-packages/pip/_internal/locations.py", line 11, in <module>
    from distutils.command.install import SCHEME_KEYS  # type: ignore
  File "/usr/lib/python3.7/distutils/command/install.py", line 9, in <module>
    from distutils.core import Command
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
ValueError: bad marshal data (unknown type code)
`

**Comment by WGandy** [comment]
Hmm.  Running:
`sudo find /usr -name '*.pyc' -delete`
Seems to fix this. I was able to run
`pip3 install tkinterweb`
and it installed pillow and tkinterweb ok.  

So, it might be some bad sauce left from a previous operation?

**Comment by Andereoo** [comment]
Hi @WGandy ,

Thanks for letting me know about this. Unfortunately, I can't seem to reproduce this on my end.  If `sudo find /usr -name '*.pyc' -delete` fixes the problem, it looks like you might just have some bad files from a previous installation of some sort. Perhaps there's a similar command for your Mac?

**Comment by WGandy** [comment]
Yes, I believe that's basically what I did to resolve it on the Mac. It does seem to be caused by something else but since it was triggered on both platforms when I tried to install tkinterweb, I think it would be good to have this mentioned in the issue history.

**Comment by Andereoo** [comment]
Sounds good!
