### ISSUE TITLE
newimage() missing 1 required positional argument: 'invert'

### ISSUE THREAD

**Issue by rphuang** [Andereoo/TkinterWeb#49]
htmlwidgets.py line 169 is missing the invert argument.

**Comment by rphuang** [comment]
Thanks for providing the package.
I was able to use TkinterWeb on Windows machine except the newimage() issue. However, I got an error on Raspberry Pi with Tkhtml:
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/tkinterweb/bindings.py", line 84, in __init__
    load_tkhtml(master, folder)
  File "/home/pi/.local/lib/python3.7/site-packages/tkinterweb/utilities.py", line 845, in load_tkhtml
    master.tk.eval("package require Tkhtml")
_tkinter.TclError: couldn't load file "/home/pi/.local/lib/python3.7/site-packages/tkinterweb/tkhtml/Linux/32-bit/Tkhtml30.so": /home/pi/.local/lib/python3.7/site-packages/tkinterweb/tkhtml/Linux/32-bit/Tkhtml30.so: cannot open shared object file: No such file or directory

I just installed with pip3 and pillow was already installed. Not sure where to get Tkhtml and pip3 install tkinterhtml didn't help.

**Comment by Andereoo** [comment]
Hi! Thanks for letting me know about this. 

The issue with the Raspberry Pi is a known issue. Take a look at https://github.com/Andereoo/TkinterWeb/issues/24. 

I fixed the `newimage` bug. Simply upgrade TkinterWeb and let me know if it works!
