### ISSUE TITLE
load_file on Windows not possible

### ISSUE THREAD

**Issue by Cathnan** [Andereoo/TkinterWeb#76]
I'm trying to load a local hello world html file using file_url. But execution of the program stops with an error. The error is:

Traceback (most recent call last):
  File "p:\VSCode-Server-Workspaces\Python_Projects\tests\GeoPy Test.py", line 28, in <module>
    frame.load_file(tempFilePath)
  File "C:\Users\heiko\AppData\Local\Programs\Python\Python311\Lib\site-packages\tkinterweb\htmlwidgets.py", line 151, in load_file
    file_url = str(file_url).split("/", 1)[1]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

Do I have to prepare paths on windows in a specific way? The path given to load_file was: path.join(sys.path[0], 'basic_html.HTML')

I'm running windows 11 22H2 Build 22621.1992 and Python 3.11.0

**Comment by VladVP** [comment]
You have to add the local file protocol before the path, i.e. `file://`. I believe there is a HtmlFrame method that does this automatically though.

(note: I'm not the author, I just had the same problem recently)

**Comment by Andereoo** [comment]
Hi @aponigricon @Cathnan thanks for bringing this to my attention. I've tweaked the logic for loading files; it should work now. Try upgrading TkinterWeb and let me know if it works for you!
