### ISSUE TITLE
AttributeError: module 'os' has no attribute 'uname'

### ISSUE THREAD

**Issue by imvickykumar999** [Andereoo/TkinterWeb#89]
```python
from tkinterweb import HtmlFrame #import the HTML browser
try:
  import tkinter as tk #python3
except ImportError:
  import Tkinter as tk #python2

root = tk.Tk() #create the tkinter window
frame = HtmlFrame(root) #create HTML browser

frame.load_website("http://tkhtml.tcl.tk/tkhtml.html") #load a website
frame.pack(fill="both", expand=True) #attach the HtmlFrame widget to the parent window
root.mainloop()
```

    Traceback (most recent call last):
      File "...\web_view.py", line 8, in <module>
        frame = HtmlFrame(root) #create HTML browser
      File "C:\Users\Vicky\anaconda3\Lib\site-packages\tkinterweb\htmlwidgets.py", line 56, in __init__
        self.html = html = TkinterWeb(self, message_func, HtmlFrame)
      File "C:\Users\Vicky\anaconda3\Lib\site-packages\tkinterweb\bindings.py", line 85, in __init__
        folder = get_tkhtml_folder()
      File "C:\Users\Vicky\anaconda3\Lib\site-packages\tkinterweb\utilities.py", line 976, in get_tkhtml_folder
        if "arm" in os.uname()[-1]: # for Raspberry Pi (#24)
    AttributeError: module 'os' has no attribute 'uname'

**Comment by Andereoo** [comment]
Hi! Thanks for letting me know about this. I just fixed the issue; let me know if it works now!

**Comment by imvickykumar999** [comment]
> Hi! Thanks for letting me know about this. I just fixed the issue; let me know if it works now!

Great, it worked now.
