### ISSUE TITLE
"RuntimeError: main thread is not in main loop" when trying to load an image that loads elsewhere

### ISSUE THREAD

**Issue by Zamy846692** [Andereoo/TkinterWeb#90]
```
>>> from tkinterweb import HtmlFrame
>>> from tkinter import Tk
>>> root=Tk()
>>> frame=HtmlFrame(root)
Starting TkinterWeb for 64-bit Windows with Python 3.9.13.

Tkhtml3 successfully loaded from C:\Users\[X]\src\tkinterweb\tkinterweb\tkhtml\Windows\64-bit.

Welcome to TkinterWeb 3.23! 
https://github.com/Andereoo/TkinterWeb

Debugging messages are enabled. 
Use the parameter `messages_enabled = False` when calling HtmlFrame() to disable these messages.

>>> frame.load_html('<img src="https://upload.wikimedia.org/wikipedia/commons/f/fc/Cthulhu3.jpg" width="500">')
>>> Fetching image: https://upload.wikimedia.org/wikipedia/commons/f/fc/Cthulhu3.jpg.

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\[X]\src\tkinterweb\tkinterweb\bindings.py", line 1076, in fetch_images
    image, error = newimage(data, name, filetype, self.image_inversion_enabled)    
  File "C:\Users\[X]\src\tkinterweb\tkinterweb\imageutils.py", line 130, in newimage
    image = PhotoImage(data=data, name=name)
  File "C:\Users\[X]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\PIL\ImageTk.py", line 125, in __init__
    self.__photo = tkinter.PhotoImage(**kw)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 4064, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 4009, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
RuntimeError: main thread is not in main loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\[X]\src\tkinterweb\tkinterweb\bindings.py", line 1097, in fetch_images
    self.load_alt_image(url, name)
  File "C:\Users\[X]\src\tkinterweb\tkinterweb\bindings.py", line 1054, in load_alt_image
    nodebox = self.bbox(node)
  File "C:\Users\[X]\src\tkinterweb\tkinterweb\bindings.py", line 421, in bbox
    return self.tk.call(self._w, "bbox", node)
RuntimeError: main thread is not in main loop
Exception ignored in: <function PhotoImage.__del__ at 0x000001F78C0E0D30>
Traceback (most recent call last):
  File "C:\Users\[X]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\PIL\ImageTk.py", line 131, in __del__
    name = self.__photo.name
AttributeError: 'PhotoImage' object has no attribute '_PhotoImage__photo'
```
The strange thing is that if `<img src="https://upload.wikimedia.org/wikipedia/commons/f/fc/Cthulhu3.jpg" width="500">` is loaded in https://www.w3schools.com/html/tryit.asp?filename=tryhtml_editor, the image loads perfectly.

And yes, when I tried  it with another URI / URL the same thing happened.

**Comment by Andereoo** [comment]
Try setting `frame.set_maximum_thread_count(0)`.

**Comment by Zamy846692** [comment]
Added `root.mainloop()` and it worked fine
